### ISSUE TITLE
The RTD hook does not work yet

### ISSUE THREAD

**Issue by andy-maier** [nir0s/distro#117]
RTD's latest version is tied to the master branch, but none of the updates to the master branch triggered an RTD run.

I have triggered the RTD build manually for both latest and stable.

Something must still be wrong with the web hook.

**Comment by nir0s** [comment]
Did you put the docs under your RTD account?

**Comment by andy-maier** [comment]
I used my RTD account to create the `ld` project over there, but I added you as well.
I think with the project rename, it is probably best if you create a new `distro` project at RTD.

**Comment by nir0s** [comment]
Works now.
