### ISSUE TITLE
Use twine to release to PyPI

### ISSUE THREAD

**Issue by andy-maier** [nir0s/distro#121]
I learned that the `twine` package has two advantages over `setup.py upload`:
- It uses encrypted communication with PyPI (setup.py added that too at some point, but I think not for Pyhton 2.6).
- It creates metadata on PyPI for the package dependencies. This results in a human readable section on the PyPI page, and I believe it also improves the machine-readable metadata about the dependencies.

**Comment by nir0s** [comment]
I actually started using twine just recently. It's really nice. I'm all for it.

**Comment by andy-maier** [comment]
I recently switched to twine in another project, and can contribute a PR to distro, soon.

**Comment by nir0s** [comment]
FYI, I already released a wheel using twine.. just didn't change the Makefile to do that. You're invited :)
