### ISSUE TITLE
Using `distro` in setup.py

### ISSUE THREAD

**Issue by AbdealiJK** [nir0s/distro#132]
Hi, I want to use `distro` to choose what to do in `setup.py`. I was wondering if there's some recommended way of doing this ?

The ideas we've thought of:
 - Using `setup_requires`, We're not sure this is a good method of doing it - There have been quite a few bugs with it (On windows, old versions of pip, etc.)
 - There was a suggestion of directly downloading https://github.com/nir0s/distro/blob/master/distro.py and importing that using urllib.

I wanted to ensure that I use the recommended way so that the app doesn't break later.

**Comment by AbdealiJK** [comment]
Bump, would love some input on this ?

**Comment by nir0s** [comment]
So, I haven't heard of someone using distro in setup.py yet so it's hard for me to tell you what's the "recommended" way of doing that. `setup_requires` sounds like a good idea though I'm not familiar with its windows breakages. 

If you know you have `pip` in your environment, you can call subprocess to install distro via pip (I wouldn't use `pip` directly from Python as its API is not official - thus the subprocess method) and then import it. somewhat hacky, but will work cross platform and should never break.

**Comment by AbdealiJK** [comment]
Nod, I found https://bitbucket.org/dholth/setup-requires which was mentioned in https://github.com/pypa/pip/issues/1820 which describes that rather than using `setup_requires` a subprocess invoking `pip` may be the best bet for reliability.

**Comment by nir0s** [comment]
I would appreciate a PR for the docs stating that as a use case and how you solved it eventually.

**Comment by AbdealiJK** [comment]
@nir0s Agree, I'll do that after I have sufficiently tested the method I'm using right now.
I also noticed that there's an issue in pip and pip may soon depend on `distro` ... https://github.com/pypa/pip/issues/3823

So, in that case maybe we wouldn't even need that extra documentation as distro would be available due to pip itself ?

**Comment by andy-maier** [comment]
If pip is ready to integrate distro (as indicated in https://github.com/pypa/pip/issues/3823), then I think we should release distro 1.0.0, to make it clear that the API is stable from now on (at least within 1.x.x).

**Comment by nir0s** [comment]
Sounds reasonable to me.

**Comment by nir0s** [comment]
@andy-maier , pip already merged 0.6.0. I guess we should still release 1.0.0 after we add the CLI. Does that make sense?

**Comment by nir0s** [comment]
@AbdealiJK, any updates on this? Interested in submitting that PR or can I close this?

**Comment by AbdealiJK** [comment]
I'm a bit busy right now, so no PR at the moment.

To give a brief idea for others who have the same issue, I had to call pip install using `subprocess` to install the package to the current directory - https://github.com/pywikibot-catfiles/file-metadata/blob/master/setupdeps.py#L49
This seems to work fine (although `pip install` is called twice)

There seems to be no elegant solution at this time that I was able to use without problems.
