### ISSUE TITLE
Add the ability to run the module directly

### ISSUE THREAD

**Issue by nir0s** [nir0s/distro#133]
For people who don't want to use Python directly, it might be a good idea to provide a way to run:

```shell
python -m distro
```

I think the output should be that of `distro.info()` but can't decide whether we should allow the `pretty` and `best` flags.

Maybe we should start from info and, according to user demand, add additional options.

**Comment by nir0s** [comment]
#134 implements this and contains some last code adjustments for the 1.0.0 release.

**Comment by MartijnBraam** [comment]
Maybe it's better to output something more human readable when running distro directly and some command line flag to output a json format if you want to parse it with bash. 

I've used the distro multiple times to find out what kind of Linux box I'm currently on.

If added a simple command line interface in 9c1143f3b6487c963fc1d89c7b675c3d7742913f that outputs the pretty name / version by default and outputs json when you supply the --json parameter

**Comment by nir0s** [comment]
Good idea. Just thought we're start from simple. But I agree, this is better.

**Comment by nir0s** [comment]
#134 solves this by adding a new CLI
