### ISSUE TITLE
OpenELEC 6.0.3 results

### ISSUE THREAD

**Issue by amosshapira** [nir0s/distro#138]
On OpenELEC 6.0.3 (http://openelec.tv/):
<br />`
<br /># python
<br />Python 2.7.3 (default, Mar  1 2016, 02:15:45)
<br />[GCC 4.9.3] on linux2
<br />Type "help", "copyright", "credits" or "license" for more information.
<br />>>> import distro
<br />>>> distro.linux_distribution()
<br />(u'OpenELEC', u'6.0', '')
<br />>>>
<br />`
<br />`distro` is not installed since there is no `pip`. I used it from the extracted root directory of the master.tar.gz download.
<br />`
<br /># lsb_release
<br />OpenELEC (official) - Version: 6.0.3
<br />`
<br />What else do you need?

**Comment by amosshapira** [comment]
`lsb_release` is just a two-line script which prints `$PRETTY_NAME` after sourcing `/etc/os-release`, here is the content of `/etc/os-release`:
```
# cat /etc/os-release
NAME="OpenELEC"
VERSION="6.0.3"
ID="openelec"
VERSION_ID="6.0"
PRETTY_NAME="OpenELEC (official) - Version: 6.0.3"
HOME_URL="http://www.openelec.tv"
BUG_REPORT_URL="https://github.com/OpenELEC/OpenELEC.tv"
OPENELEC_ARCH="imx6.arm"
OPENELEC_BUILD="official"
```

**Comment by nir0s** [comment]
Thanks. I'll verify that it provides the correct info

**Comment by nir0s** [comment]
Test added with v1.0.3
