### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by xsuchy** [nir0s/distro#139]
Can you please include LICENSE file in tar file, next time you will do the release? Probably by putting it in setup.py. It will easy its packaging in Fedora (I am doing it right now).

**Comment by ignatenkobrain** [comment]
no, it should not be installed, it should be distributed along with PyPI tarball.

**Comment by bachp** [comment]
I would also like to see this included as I'm packaging this for OpenEmbedded. Thanks.

**Comment by nir0s** [comment]
v1.0.2 now contains the license file.
