### ISSUE TITLE
Provide an API for returning a list of all available init systems

### ISSUE THREAD

**Issue by nir0s** [nir0s/distro#142]
Much like any other piece of information distro returns, init systems vary between distributions. It's true that nowadays most move towards systemd. Still, upstart, sysvinit, openrc, runit and supervisor are available depending on how "legacy" you are or if you're using non-standard init systems.

i suggest we add something like this

``` python
init_systems = distro.init()
# alternatively, distro.init_systems()
print(init_systems)
# ['upstart', 'systemd']
```

will return a list of standardized names of the init systems available on the machine you're running on.
We should probably somehow address the versions also as, for example, upstart is different between 1.10 and 0.6.5.

We can identify which init systems are available either via available executables or existing paths.
https://github.com/nir0s/serv/blob/master/serv/init/systemd.py#L185, for instance, shows how to check whether systemctl (systemd) is available.

I also suggest we provide a hierarchy between systems, as, for instance, it makes more sense to return `['systemd', 'upstart']` than `['upstart', 'systemd']` as the first usable system should probably be the most recent one (WDYT?)

Providing this functionality will allow systems to automatically create configuration for a service on the relevant system, know which commands they can run or which API to query to get the status of running services, etc.

**Comment by nir0s** [comment]
Thoughts?

**Comment by MartijnBraam** [comment]
What system has multiple init systems? All I can think of is ['systemd', 'sysv'] because the sysv compatibility in systemd. 

Maybe the order should be based on a list of init systems in the distro module as default that can be overriden my a list passed to distro.init()

Also maybe this should be renamed to distro.service_manager() since that is the part that the users of this module most likely care about (getting the location to put their service files).

**Comment by nir0s** [comment]
First of all, even if it only returns a single init system, it would still abstract the discovery method from the user, which is good. Now, for instance, 14.04 has systemd (sort of), upstart and sysvinit. https://github.com/nir0s/serv implements an abstraction of init systems and it would've been great if I didn't have to implement the discovery process there.

Regarding the location to put their service files in, maybe we can return a list of named tuples:

```python
distro.init()

[
    Systemd(name='systemd', service_path='/lib/systemd/system', envs_path='/etc/sysconfig'), 
    Upstart(...)
]
```

**Comment by nir0s** [comment]
Waste of breath I guess.
