### ISSUE TITLE
Provide an API for getting a list of available package managers

### ISSUE THREAD

**Issue by nir0s** [nir0s/distro#143]

**Comment by MartijnBraam** [comment]
Does this include language specific package managers like pip, gem and npm?

**Comment by nir0s** [comment]
Well, these aren't distro specific.. And can practically be installed
anywhere..

**Comment by MartijnBraam** [comment]
Technically no package manager is distro specific. On the other hand if you want to call pip for python 3 in debian 7 or 8 you have to guess the executable because it doesn't symlink pip3 to the correct version.

**Comment by nir0s** [comment]
True. What we can do, though, is work according to a certain hierarchy of where we think they might be.

**Comment by nir0s** [comment]
@kdeldycke, it would be great if you could open a PR which will use mpm to allow distro to list package managers when you're done.

**Comment by kdeldycke** [comment]
There's still a lot of work on the Linux side of `mpm` but will get there eventually. At which point I'll be happy to open a PR.

In the mean time, do you have a list of minimal requirements that might makes you consider `mpm` as a good solution?

**Comment by nir0s** [comment]
Well, in distro's context, all I would like to know is which package managers are installed on the current system. I'm trying to think a bit farther (i.e. their paths, etc..), but I think clutter might ruin distro's simple nature.

**Comment by kdeldycke** [comment]
Thanks @nir0s for the feedback. Support of package manager is indeed a Pandora's box. I'm worried you can't really implement something useful without investing time... :weary:

**Comment by nir0s** [comment]
I don't quite understand what you mean. Does it mean you don't intend  to provide an API for retrieving a list of all available package managers?

**Comment by kdeldycke** [comment]
Sorry for that cryptic comment! :sweat_smile:

I was just trying to acknowledge the difficulty of the task. And I'm really happy about the prospect of having `distro` relying on my modest `mpm` module! :smiley:

**Comment by funkyfuture** [comment]
i have the suspcion that this may increase the maintanance effort needed to keep this package up-to-date quiet a lot and would suggest another package for that question. same with #142.

**Comment by nir0s** [comment]
I'll close this. In retrospect, seems like a bad idea.
