### ISSUE TITLE
distro crashes when non-ASCII character appears in lsb_release

### ISSUE THREAD

**Issue by adamjstewart** [nir0s/distro#151]
We're using the `distro` package for linux distribution detection in a package manager called [Spack](https://github.com/LLNL/spack). Unfortunately, one of our users discovered a bug that causes distro to crash with the following error message:
```
File "distro.py", line 1049, in 
    _distroi = LinuxDistribution()
File "distro.py", line 595, in init
    if include_lsb else {}
File "distro.py", line 921, in _lsb_release_info
    out, err = out.decode('ascii'), err.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 250: ordinal not in range(128)
```
Here is their lsb_release:
```
$ lsb_release -a
LSB Version: :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description: Fedora release 19 (Schrödinger’s Cat)
Release: 19
Codename: Schrödinger’sCat
```
I assume the problem is that `distro` can't handle the `ö` in Schrödinger’s Cat.

**Comment by nir0s** [comment]
Which version of distro are you using? We no longer decode using ascii.. but rather utf-8.

https://github.com/nir0s/distro/blob/master/distro.py#L923

**Comment by nir0s** [comment]
We also have a test covering that.

https://github.com/nir0s/distro/blob/master/tests/resources/distros/fedora19/etc/fedora-release

**Comment by adamjstewart** [comment]
I'm not sure what version we are using, @tgamblin was the one who added the module. It looks pretty close to the latest release on GitHub (`v0.6.0`) with a minor fix in #148. I noticed that there is a newer release on PyPi, so I'll update to that release and let you know if that fixes the problem.

**Comment by nir0s** [comment]
Yup. 0.6.0 has the bug. 1.0.1 solves it.

**Comment by tgamblin** [comment]
@adamjstewart we can probably close this
