### ISSUE TITLE
tag releases on github

### ISSUE THREAD

**Issue by ignatenkobrain** [nir0s/distro#153]
would be nice to have real source for releases as a tags in git.

**Comment by nir0s** [comment]
My bad. Will take care of that for 1.0.1 onwards.

**Comment by ignatenkobrain** [comment]
@nir0s note that you can do this in past. you just specify commit from which you want to make tag.

Thanks!

**Comment by nir0s** [comment]
Release v1.0.0 and v1.0.0. Will make sure all future versions are also tagged.
