### ISSUE TITLE
Remove ImportError if sys.platform is not Linux.

### ISSUE THREAD

**Issue by SethMichaelLarson** [nir0s/distro#164]
I would like to use the `distro` module for a more abstract use-case by sub-classing the `LinuxDistribution` and replacing the `_get_*_release_info()` methods with my own custom methods. However there is currently a check against `sys.platform` at the top of the file which prevents this abstract code from running in a non-Linux platform, which is required for the project that I am currently working on.

I would really prefer to not vendor the module and make changes myself to make sure that future improvements do not require me to re-implement my vendored module. Plus it will make any improvements I would like in the module to be done in upstream rather than my own in-project fork. :)

Is there any way this error could be removed? I realize this would probably require a major version tick which is a shame. :/

It's fine to close this issue if it's something you won't do, I understand. :) I will still contribute back any improvements I make to this repository.

**Comment by nir0s** [comment]
I'll have to think this through. Just wondering. Can't you just do something like

```python
try:
    current_platform = sys.platform
    sys.platform = 'linux'
    import distro
finally:
    sys.platform = current_platform
```

Let's think about an implementation together that will allow people to do what you're looking to do but not require removing this (probably by allowing people to ignore this check, which will still be done by default.)

**Comment by SethMichaelLarson** [comment]
That's true I can do something like that. :) I'll stick with that for now.
I'm fine with keeping the module as-is, figured I'd just quickly ask before doing a little hack haha :)

**Comment by nir0s** [comment]
Alright. I'll close this. If it's still an issue for some reason, i'll reopen it.
