### ISSUE TITLE
Please get packaged in Debian

### ISSUE THREAD

**Issue by hartwork** [nir0s/distro#169]
Hi!

Cool to see this effort, thanks for working on this project!

For me to really add `distro` as a dependency to existing code parsing `lsb_release` output at the moment, I would need it to go into core Debian, at least. Is someone working on that?

Best, Sebastian

PS: I ran into `distro` from the new new packages feed of Gentoo. So `distro` has an official package `dev-python/distro` in Gentoo for a few days now, if you haven't heard about it: https://github.com/gentoo/gentoo/commit/044a63e1562dd413a4b1d438e769057a6630b7e8

**Comment by nir0s** [comment]
Cool. Didn't know that.

We haven't been working on distributing it under debian, but I don't see why we couldn't. Are you interested in contributing that?

**Comment by hartwork** [comment]
Hi!
It takes (any kind of) a [Debian maintainer](https://wiki.debian.org/Maintainers) to get *into* Debian.

**Comment by nir0s** [comment]
hehe. I should've looked it up. Anyway.. i'll try to become one.

**Comment by nir0s** [comment]
Apparently, https://packages.debian.org/sid/main/python-distro

**Comment by hartwork** [comment]
I did search back then, found https://packages.debian.org/sid/python-distro-info only, not sure why. My bad, excellent to have it in! It could use an update though. Anyway, this is good news!
Best, Sebastian

**Comment by nir0s** [comment]
Apparently, it's also distributed here:

* https://admin.fedoraproject.org/pkgdb/package/rpms/python-distro/
* https://centos.pkgs.org/7/epel-x86_64/python2-distro-1.0.2-3.el7.noarch.rpm.html
* https://aur.archlinux.org/packages/python-distro/
* https://launchpad.net/ubuntu/+source/python-distro

Nice!

**Comment by MartijnBraam** [comment]
Hmm the description for https://packages.debian.org/sid/main/python3-distro is not correct. It says:

> This is the Python 2 version of the library.
