### ISSUE TITLE
Maybe link to GitHub repo (and PyPI) from the doc pages

### ISSUE THREAD

**Issue by hartwork** [nir0s/distro#170]
Hi!

The http://distro.readthedocs.io/en/latest/ docs do not seem to advertise this GitHub repo and or the PyPI package page. Right now, you need to look at the HTML or to search the web to find these places. I think "Overview and motivation" would be a god place to add links like that so they are found quickly.

Thanks and best, Sebastian

**Comment by nir0s** [comment]
Sure.

**Comment by nir0s** [comment]
Fixed with 1.0.3
