### ISSUE TITLE
Error when /etc is not readable

### ISSUE THREAD

**Issue by dstufft** [nir0s/distro#174]
Originally reported in https://github.com/pypa/pip/issues/4320.

> Hi,
> I'm doing scientific computations on a Computer cluster. When the sysadmin decided to remove read permissions from /etc pip stopped working, because` os.listdir(_UNIXCONFDIR)` in  [distro.py ](https://github.com/pypa/pip/blob/master/pip/_vendor/distro.py#L984) fails.
>
> As a quick fix I changed the following in my local pip installation:
> ```python
> try:
>     basenames = os.listdir(_UNIXCONFDIR)
>     # We sort for repeatability in cases where there are multiple
>     # distro specific files; e.g. CentOS, Oracle, Enterprise all
>     # containing `redhat-release` on top of their own.
>     basenames.sort()
> except OSError:
>     basenames = ["os-release"]
> ```
> This of course requires `/etc/os-release` to be readable.
> I just wanted to share this in case someone runs into the same problem!

**Comment by SethMichaelLarson** [comment]
So on this user's system `/etc` is not readable but `/etc/os-release` is readable? There's a unique configuration.

**Comment by dstufft** [comment]
Possibly yes. I'm more concerned about the case where someone has their /etc unreadable completely though tbh. Currently it will fail trying to list the directory.

**Comment by SethMichaelLarson** [comment]
@dstufft Of course, if you wanted to review #175 I just submitted as a fix for this.

**Comment by nir0s** [comment]
Released v1.0.4 solving this issue.

**Comment by dstufft** [comment]
Thanks a lot!
