### ISSUE TITLE
Debian stretch doesn't provide a version number

### ISSUE THREAD

**Issue by nir0s** [nir0s/distro#187]
Its os-release file doesn't have a version number. To aid users, I would actually add it as part of the currently ongoing work on distro inconsistency handling.

WDYT?

**Comment by SethMichaelLarson** [comment]
:+1:

**Comment by SethMichaelLarson** [comment]
This can be closed.

**Comment by nir0s** [comment]
The stable build is identified correctly. Closing.

**Comment by nir0s** [comment]
The stable build is identified correctly. Closing.

**Comment by nir0s** [comment]
The stable build is identified correctly. Closing.

**Comment by nir0s** [comment]
The stable build is identified correctly. Closing.
