### ISSUE TITLE
Add BSD support

### ISSUE THREAD

**Issue by woodsb02** [nir0s/distro#191]
Would it be appropriate to add support for detecting the different families of BSD?
- FreeBSD
- NetBSD
- OpenBSD
- DragonFlyBSD
- TrueOS

**Comment by SethMichaelLarson** [comment]
I would love to see this. Do you have access to a VirtualBox or other virtualization software @woodsb02 ?

**Comment by krytarowski** [comment]
Do you mean vbox on BSD as host?

**Comment by woodsb02** [comment]
I can spin up a FreeBSD guest within my Vultr account, and give you access, if that would help with testing?
I also use the FreeBSD bhyve type 2 hypervisor at home for my own testing, but can't give external access to this.

**Comment by SethMichaelLarson** [comment]
Well I could do the virtualization myself. :) I was just wondering if you were up to making the contribution yourself.

**Comment by nir0s** [comment]
It would be awesome to support these. I would need a contribute for that though as I don't currently have the time to invest.

Anyone? :)

**Comment by Armonaut** [comment]
I can work on this, I'll fire up a Virtualbox instance and see what I can do!

**Comment by SethMichaelLarson** [comment]
I'll try to make a dent in this!

**Comment by SethMichaelLarson** [comment]
So I've installed and configured an OpenBSD installation and I've found that there is no `/etc/*-release` files and no lsb-release installed by default. It seems that the only way to get version info is via `uname -rs` which outputs `OpenBSD 6.2`. So perhaps we should try that if `lsb-release` isn't installed?

**Comment by krytarowski** [comment]
lsb stands for LINUX standard base.

On BSD use uname. If you really need to parse userland version, there is an option to grep for version in headers.

```
$ awk '/^#define/ && /__NetBSD_Version__/ {print $6}' /usr/include/sys/param.h  
8.99.7
```

**Comment by SethMichaelLarson** [comment]
Thanks for the tip, I was doubtful LSB would be available but was surprised that there wasn't any release info in `/etc`. I think I'll go down the `uname -rs` route.

**Comment by woodsb02** [comment]
Note that on FreeBSD you can use the command "freebsd-version -k" to give you the same details of the kernel version. The helpful part is that if you want the userland details, you use "freebsd-version -u" (it can be different to the kernel if patches have come out for a release that only affect either kernel or userland).

**Comment by woodsb02** [comment]
Note that distro 1.2.0 has now been added to the FreeBSD ports collection, with Seth's patch in #207. If the BSD implementation changes, we can easily update the patch in the ports tree, but at least this has it working on FreeBSD :)
https://www.freshports.org/sysutils/py-distro

**Comment by krytarowski** [comment]
Why would be there /etc/*release, it's a Linux specific file. BSD are one - from the kernel to userland, and in typical scenarios uname(1) retrieves the version for everything at once.

**Comment by SethMichaelLarson** [comment]
I was reporting information back. I've never investigated or booted into *BSD before, so I'm not sure how I would know that before investigating and learning myself.
