### ISSUE TITLE
Testcase for Amazon Linux is missing

### ISSUE THREAD

**Issue by andy-maier** [nir0s/distro#74]
Amazon Linux (ID: `amazon`) is one of the distros with a reliable ID. A testcase should be added.

If you want to help, it is sufficient to post to this issue:
* The content of the `/etc/os-release` file, if any.
* The file names and content of the `/etc/*release` and `/etc/*version` files, if any.
* The output of the command: `lsb_release -a`, if available.

**Comment by nir0s** [comment]
The Amazon Linux 2016.03 image contains an os-release file while the 2014.03 one only contains a system-release file, which we do not handle. Before this is merged, I suggest we discuss this.

**Comment by nir0s** [comment]
Will open an issue regarding system-release files in general
