### ISSUE TITLE
Testcase for CloudLinux OS is missing

### ISSUE THREAD

**Issue by andy-maier** [nir0s/distro#75]
CloudLinux OS (ID: `cloudlinux`) is one of the distros with a reliable ID. A testcase should be added.

If you want to help, it is sufficient to post to this issue:
- The content of the `/etc/os-release` file, if any.
- The file names and content of the `/etc/*release` and `/etc/*version` files, if any.
- The output of the command: `lsb_release -a`, if available.

**Comment by nir0s** [comment]
Thanks @SethMichaelLarson. CloudLinux 5, 6 and 7 tested.
